name: Keyra
description: "A Flutter app for AI-generated children's books"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  googleapis: ^12.0.0
  googleapis_auth: ^1.4.1
  audioplayers: ^5.2.1
  path_provider: ^2.1.1
  http: ^1.2.2
  timeago: ^3.6.0
  uuid: ^4.2.2
  cupertino_icons: ^1.0.2
  go_router: ^13.0.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1
  dartz: ^0.10.1
  get_it: ^7.6.4
  injectable: ^2.3.2
  shared_preferences: ^2.3.5
  flutter_localizations:
    sdk: flutter
  intl: any
  flutter_native_splash: ^2.3.8
  flutter_launcher_icons: ^0.13.1
  package_info_plus: ^8.1.2
  url_launcher: ^6.2.2
  image_picker: ^1.0.5
  file_picker: ^8.1.7
  path: ^1.8.3
  flutter_image_compress: ^2.1.0
  cached_network_image: ^3.3.0
  flutter_cache_manager: ^3.4.1
  photo_view: ^0.14.0
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  permission_handler: ^11.1.0
  device_info_plus: ^9.1.1
  connectivity_plus: ^5.0.2
  logger: ^2.0.2+1
  dio: ^5.4.0
  
  # Hive
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  easy_localization: ^3.0.3
  sign_in_with_apple: ^5.0.0
  crypto: ^3.0.3
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  cloud_firestore: ^5.4.0
  firebase_storage: ^12.2.0
  cloud_functions: ^5.2.0
  _flutterfire_internals: ^1.3.49
  google_sign_in: 6.2.2
  hugeicons: ^0.0.7
  japanese_word_tokenizer: ^0.0.3
  ruby_text: ^3.0.3
  xml: ^6.3.0
  sqflite: ^2.3.0
  archive: ^3.4.9
  flutter_dotenv: ^5.1.0
  lottie: 2.7.0
  flip_card: ^0.7.0
  rxdart: ^0.27.7
  in_app_purchase: ^3.1.13
  in_app_purchase_storekit: ^0.3.6+13
  in_app_purchase_android: ^0.3.6+13
  flutter_local_notifications: ^18.0.1
  provider: ^6.1.2
  battery_plus: ^5.0.2
  characters: ^1.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  injectable_generator: ^2.4.1
  bloc_test: ^9.1.5
  mockito: ^5.4.3
  mocktail: ^1.0.0
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/images/onboarding/
    - assets/images/login/
    - assets/images/navbar/
    - assets/images/splashscreen/
    - assets/images/ministats/
    - assets/subscription/
    - assets/fonts/
    - assets/flags/
    - assets/loader/
    - assets/audio/
    - assets/badge/
    - assets/audio/books/
    - assets/audio/books/magic_forest/
    - assets/audio/books/magic_forest/de/
    - assets/audio/books/magic_forest/en/
    - assets/audio/books/magic_forest/es/
    - assets/audio/books/magic_forest/fr/
    - assets/audio/books/magic_forest/it/
    - assets/config/google_tts_credentials.json
    - assets/jmdict/dictionary.json
    - assets/kanjidict/dictionary.json

  fonts:
    - family: FascinateInline
      fonts:
        - asset: assets/fonts/FascinateInline-Regular.ttf
          weight: 400
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
    - family: Playwrite
      fonts:
        - asset: assets/fonts/PlaywriteAUSA-Regular.ttf
          weight: 400
        - asset: assets/fonts/PlaywriteAUSA-Light.ttf
          weight: 300
        - asset: assets/fonts/PlaywriteAUSA-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/PlaywriteAUSA-Thin.ttf
          weight: 100
    - family: PaytoneOne
      fonts:
        - asset: assets/fonts/PaytoneOne-Regular.ttf
          weight: 400
    - family: SpicyRice
      fonts:
        - asset: assets/fonts/SpicyRice-Regular.ttf
          weight: 400
    - family: RubikVinyl
      fonts:
        - asset: assets/fonts/RubikVinyl-Regular.ttf
          weight: 400
    - family: Rowdies
      fonts:
        - asset: assets/fonts/Rowdies-Regular.ttf
          weight: 400
        - asset: assets/fonts/Rowdies-Light.ttf
          weight: 300
        - asset: assets/fonts/Rowdies-Bold.ttf
          weight: 700
